version: "3.3"
services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    links:
      - redis:redis
    depends_on:
      - redis
    command: sh -c "npm install && npm start"
    
  redis:
        image: redis:latest
        restart: always    
        ports:
          - "6379:6379"
        command: "redis-server"

    